apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: message-server
    spec:
      containers:
        - image: asia.gcr.io/grpc-message-service/server:latest
          imagePullPolicy: Always
          name: message-server
          ports:
            - containerPort: 50101
