apiVersion: v1
kind: Service
metadata:
  name: message-server
spec:
  type: LoadBalancer
  selector:
    name: message-server
  ports:
    - port: 8000
      name: http
    - port: 9000
      name: http2
