// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateConversationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{0}
}
func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(dst, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

type Conversation struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{1}
}
func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (dst *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(dst, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Conversation) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type CreateMessageRequest struct {
	// Resource name of the parent conversation.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Message to be created. The name and create_time are set on server side, so client must not set.
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{2}
}
func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (dst *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(dst, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Message struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The someone who sent the message.
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// The body of message.
	Body                 string               `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type GetMessagesRequest struct {
	// Resource name of the parent conversation.
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{4}
}
func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(dst, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type Messages struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e4408603590bbe0f, []int{5}
}
func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (dst *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(dst, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateConversationRequest)(nil), "message.CreateConversationRequest")
	proto.RegisterType((*Conversation)(nil), "message.Conversation")
	proto.RegisterType((*CreateMessageRequest)(nil), "message.CreateMessageRequest")
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*GetMessagesRequest)(nil), "message.GetMessagesRequest")
	proto.RegisterType((*Messages)(nil), "message.Messages")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*Messages, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	out := new(Conversation)
	err := c.cc.Invoke(ctx, "/message.MessageService/CreateConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.MessageService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*Messages, error) {
	out := new(Messages)
	err := c.cc.Invoke(ctx, "/message.MessageService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	GetMessages(context.Context, *GetMessagesRequest) (*Messages, error)
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/CreateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CreateConversation(ctx, req.(*CreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _MessageService_CreateConversation_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _MessageService_CreateMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _MessageService_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_message_e4408603590bbe0f) }

var fileDescriptor_message_e4408603590bbe0f = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0xcf, 0xd2, 0x40,
	0x10, 0xc6, 0x53, 0xde, 0x37, 0xbc, 0x30, 0xa8, 0x91, 0x41, 0x49, 0x29, 0x1a, 0xc9, 0x26, 0x46,
	0xd2, 0x60, 0xab, 0x78, 0x31, 0x1a, 0x4f, 0x1c, 0x3c, 0x79, 0xa9, 0x9e, 0xbc, 0x90, 0x05, 0x46,
	0x52, 0x43, 0xbb, 0xb5, 0xbb, 0x90, 0x18, 0xe3, 0xc5, 0x83, 0x5f, 0xc0, 0x8f, 0xe6, 0xdd, 0x93,
	0x1f, 0xc4, 0x74, 0xff, 0x60, 0xf9, 0x63, 0xd4, 0xdb, 0xce, 0xec, 0xd3, 0xe7, 0xb7, 0xcf, 0x4c,
	0x0a, 0xbd, 0xa2, 0x14, 0x4a, 0xc4, 0x19, 0x49, 0xc9, 0xd7, 0x14, 0xe9, 0x0a, 0xaf, 0x6c, 0x19,
	0xdc, 0x59, 0x0b, 0xb1, 0xde, 0x50, 0xcc, 0x8b, 0x34, 0xe6, 0x79, 0x2e, 0x14, 0x57, 0xa9, 0xc8,
	0xa5, 0x91, 0x05, 0xf7, 0xec, 0xad, 0xae, 0x16, 0xdb, 0x77, 0xb1, 0x4a, 0x33, 0x92, 0x8a, 0x67,
	0x85, 0x11, 0xb0, 0x21, 0x0c, 0x66, 0x25, 0x71, 0x45, 0x33, 0x91, 0xef, 0xa8, 0x94, 0xfa, 0xeb,
	0x84, 0x3e, 0x6c, 0x49, 0x2a, 0x36, 0x87, 0x6b, 0xf5, 0x36, 0x22, 0x5c, 0xe6, 0x3c, 0x23, 0xdf,
	0x1b, 0x79, 0xe3, 0x76, 0xa2, 0xcf, 0xf8, 0x1c, 0x3a, 0x4b, 0x6d, 0x30, 0xaf, 0xac, 0xfd, 0xc6,
	0xc8, 0x1b, 0x77, 0xa6, 0x41, 0x64, 0xb8, 0x91, 0xe3, 0x46, 0x6f, 0x1c, 0x37, 0x01, 0x23, 0xaf,
	0x1a, 0xec, 0x2d, 0xdc, 0x32, 0xf4, 0x57, 0x26, 0x8d, 0x05, 0x63, 0x1f, 0x9a, 0x05, 0x2f, 0x29,
	0x57, 0x16, 0x65, 0x2b, 0x0c, 0xc1, 0xe5, 0xb6, 0xa0, 0x9b, 0x91, 0x1b, 0x8b, 0x73, 0x70, 0x02,
	0xf6, 0xd5, 0x83, 0x2b, 0xdb, 0x3c, 0xfb, 0xf0, 0x3e, 0x34, 0x25, 0xe5, 0x2b, 0x2a, 0xb5, 0x55,
	0x3b, 0xb1, 0x55, 0xa5, 0x5d, 0x88, 0xd5, 0x47, 0xff, 0xc2, 0x68, 0xab, 0xf3, 0x71, 0xc8, 0xcb,
	0xff, 0x0a, 0x39, 0x01, 0x7c, 0x49, 0xca, 0x3e, 0x45, 0xfe, 0x25, 0x22, 0x7b, 0x0a, 0x2d, 0x27,
	0xc5, 0x09, 0xb4, 0x6c, 0x1a, 0xe9, 0x7b, 0xa3, 0x8b, 0xb3, 0x79, 0xf7, 0x8a, 0xe9, 0x8f, 0x06,
	0xdc, 0xb0, 0xdd, 0xd7, 0x54, 0xee, 0xd2, 0x25, 0xe1, 0x7b, 0xc0, 0xd3, 0xed, 0x22, 0xdb, 0x9b,
	0xfc, 0x71, 0xf5, 0xc1, 0xed, 0xdf, 0x9a, 0xda, 0x2d, 0x1b, 0x7c, 0xf9, 0xfe, 0xf3, 0x5b, 0xa3,
	0xc7, 0xba, 0xf1, 0xee, 0x71, 0xbc, 0xac, 0xdd, 0x48, 0x2c, 0xe1, 0xfa, 0xc1, 0x2e, 0xf1, 0xee,
	0x11, 0xe6, 0x70, 0xc7, 0xc1, 0x49, 0x14, 0xf6, 0x48, 0x9b, 0x87, 0xec, 0x7e, 0x65, 0xfe, 0xc9,
	0xcc, 0xe3, 0xc5, 0x01, 0x24, 0x0e, 0x3f, 0xbb, 0xff, 0x40, 0x3e, 0xf3, 0x42, 0xdc, 0x40, 0xa7,
	0x36, 0x5a, 0x1c, 0xee, 0x2d, 0x4f, 0x07, 0x1e, 0x74, 0x8f, 0x79, 0x92, 0x3d, 0xd4, 0xc0, 0x07,
	0xf8, 0x6f, 0xc0, 0x45, 0x53, 0x2f, 0xfa, 0xc9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x1e,
	0x9f, 0xf6, 0x91, 0x03, 0x00, 0x00,
}
